using UnityEngine;
using TMPro;
using System.Collections.Generic;

public class GameManager : MonoBehaviour
{
    [Header("Settings")]
    public GameSettings settings;

    [Header("UI")]
    public TextMeshProUGUI teamNameUI;
    public TextMeshProUGUI scoreUI;
    public TextMeshProUGUI timerUI;
    public TextMeshProUGUI passUI;

    [Header("Cards")]
    public List<CardData> cards;
    public CardScript cardScript;

    private int currentTeamIndex = 0;
    private int currentCardIndex = 0;

    private int remainingPass;
    private float timer;

    private void Start()
    {
        StartTurn();
    }

    void Update()
    {
        HandleTimer();
    }

    // üîÅ TUR BA≈ûLAT
    void StartTurn()
    {
        timer = settings.roundTime;
        remainingPass = settings.maxPass;

        ShuffleCards();
        ShowCard();
        UpdateUI();
    }

    // ‚è±Ô∏è TIMER
    void HandleTimer()
    {
        timer -= Time.deltaTime;
        timerUI.text = Mathf.Ceil(timer).ToString();

        if (timer <= 0)
        {
            ChangeTeam();
        }
    }

    // üü¢ DOƒûRU
    public void CorrectAnswer()
    {
        settings.teams[currentTeamIndex].score += cards[currentCardIndex].cardScore;
        NextCard();
        UpdateUI();
    }

    // üî¥ YASAK KELƒ∞ME
    public void ForbiddenUsed()
    {
        settings.teams[currentTeamIndex].score -= cards[currentCardIndex].negativeScore;
        NextCard();
        UpdateUI();
    }

    // üü† PAS
    public void Pass()
    {
        if (remainingPass <= 0) return;

        remainingPass--;
        NextCard();
        UpdateUI();
    }

    // ‚è≠Ô∏è KART DEƒûƒ∞≈ûTƒ∞R
    void NextCard()
    {
        currentCardIndex = Random.Range(0, cards.Count);
        ShowCard();
    }

    void ShowCard()
    {
        cardScript.SetCard(cards[currentCardIndex]);
    }

    // üîÑ TAKIM DEƒûƒ∞≈û
    void ChangeTeam()
    {
        currentTeamIndex++;

        if (currentTeamIndex >= settings.teams.Length)
            currentTeamIndex = 0;

        StartTurn();
    }

    void UpdateUI()
    {
        teamNameUI.text = settings.teams[currentTeamIndex].teamName;
        scoreUI.text = settings.teams[currentTeamIndex].score.ToString();
        passUI.text = remainingPass.ToString();
    }

    // üé≤ SHUFFLE (TUR BA≈ûI)
    void ShuffleCards()
    {
        for (int i = 0; i < cards.Count; i++)
        {
            int r = Random.Range(i, cards.Count);

            CardData temp = cards[i];
            cards[i] = cards[r];
            cards[r] = temp;
        }
    }
}
